"use client"
// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { GlobalStyles } from "@mui/material";
import Navbar from "./_components/_Navbar/Navbar";
import { Provider } from "react-redux";
import { store } from "@/redex/store";
import  { Toaster } from 'react-hot-toast';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <AppRouterCacheProvider>
        <GlobalStyles styles="@layer theme, base, mui, components, utilities;" />
        <Provider store={store}>
        <Navbar></Navbar>
        {children}
         <Toaster/>
        </Provider>
      </AppRouterCacheProvider>
      </body>
    </html>
  );
}
